### ISSUE TITLE
Tracking of dependencies for releasing to opam

### ISSUE THREAD

**Issue by mbarbin** [mbarbin/vcs#1]
This issue tracks the dependencies that would need to be handled first in order to publish `vcs` to opam. Resolution may for example be any of:
- Refactor vcs to remove the dependency
- Vendor it in vcs
- Publish the dependency itself into opam
- ?

### For the library part (`vcs`, `vcs-git`)

- [x] [eio-process](https://github.com/mbarbin/eio-process) => vendored => removed
- [x] [fpath-base](https://github.com/mbarbin/fpath-base) => [release status](https://github.com/mbarbin/fpath-base/milestone/1)
- [x] [provider](https://github.com/mbarbin/provider) => [released](https://opam.ocaml.org/packages/provider/)
- [x] [union-find](https://github.com/mbarbin/union-find) => vendored => removed

### Command line interface (`volgo-vcs`)

To include the command line interface (e.g, for quick exploratory tests):

- [x] [command-unix-for-opam](https://github.com/mbarbin/command-unix-for-opam) => switched to cmdlang
- [x] [eio-writer](https://github.com/mbarbin/eio-writer) => vendored => removed
- [x] [cmdlang](https://github.com/mbarbin/cmdlang)

**Comment by mbarbin** [comment]
Re: union-find. I tried vendoring it into `vcs` but this currently creates other issues for me. Work in progress and issue tracking https://github.com/ocaml/dune/issues/10268.

**Comment by mbarbin** [comment]
The project is now available on opam with namespacing prefix "volgo". Initial release was `0.0.18` though, leaving the question of stabilizing to `0.1.0` as future work.
